### ISSUE TITLE
03 - Data Preprocessing Techniques

### ISSUE THREAD

**Issue by evanyeohboonkhai** [CertifaiAI/time-series-labs#52]
**Describe the bug**
Eg. 2.2.2 - Correct them with linear interpolation

**To Reproduce**
Run the notebooks

**Expected behavior**
It should replace with NaN value and perform interpolatiob.
It is not replaced with a zero value .

** Screenshot **
![image](https://user-images.githubusercontent.com/59526258/112809922-21752780-90ad-11eb-8a4e-ddba47c431b0.png)

**Comment by YCCertifai** [comment]
0 should be replaced by np.nan
