### ISSUE TITLE
04 - CNN_Multivariate_Univariate_SingleStep normalization issue

### ISSUE THREAD

**Issue by YCCertifai** [CertifaiAI/time-series-labs#55]
![image](https://user-images.githubusercontent.com/76682536/114830567-e853eb80-9dfe-11eb-9a2c-6c5ee2a07962.png)

![image](https://user-images.githubusercontent.com/76682536/114830746-1fc29800-9dff-11eb-978e-9a9c8ce5bcec.png)

For multivariate input data, each column should **perform normalization differently** instead of **reshape into one column** and perform scaling.

The correct way should be similar to image below:
![image](https://user-images.githubusercontent.com/76682536/114831281-c9a22480-9dff-11eb-944d-fd96f4850b9b.png)

**Comment by evanyeohboonkhai** [comment]
issue solved and close
