### ISSUE TITLE
Conda package cannot be resolved for macOS

### ISSUE THREAD

**Issue by fariskamaludin-skymind** [CertifaiAI/time-series-labs#65]
**Describe the bug**
- Package `cudatoolkit` cannot be resolved while trying to install the conda environment for macOS.

<img width="444" alt="Screenshot 2021-07-06 at 5 49 59 AM" src="https://user-images.githubusercontent.com/83570177/124520939-849af680-de20-11eb-923f-8ea8dc5bf0d3.png">

**To Reproduce**
1. Tried to create the environment based on the command `conda env create -f environment.yml`.
2. Error triggered as shown.

**Expected behavior**
- Conda environment can be created.

**Screenshots**
- After did some checking at the [Anaconda registry](https://anaconda.org/anaconda/cudatoolkit), identified that the `cudatoolkit` package only support macOS only up to version 9.0

<img width="1005" alt="Screenshot 2021-07-06 at 5 57 17 AM" src="https://user-images.githubusercontent.com/83570177/124521082-ee1b0500-de20-11eb-9fed-c812f6fc338a.png">

- Suggest to remove the set version for `cudatoolkit` package in the environment file so that it automatically download & use the compatible version for respective OSes.

<img width="271" alt="Screenshot 2021-07-06 at 5 59 46 AM" src="https://user-images.githubusercontent.com/83570177/124521208-523dc900-de21-11eb-9507-645632744332.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.7 (19H2)

**Comment by KianYang-Lee** [comment]
Taking this
